### ISSUE TITLE
Правки в конфигурациях

### ISSUE THREAD

**Issue by altynbek07** [naffiq/yii2-app-bridge#1]
- [x] Добавить в example.local.php:
- `bootstrap' => ['debug']`
- `'modules' => [
            'debug' => [
                'class' => \yii\debug\Module::className()
            ],
   ]`
------------------------------------------------------------
- [ ] Изменить кодировку на utf8mb4 в конфигурациях БД

**Comment by naffiq** [comment]
Оставим utf8, т.к. многие до сих пор базы создают в этой кодировке.
